import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header/page";
import Home from "./page";
import Pricing from "./pricing/page";
import Faq from "./about/page";
import Newsletter1 from "./newsletter/page";
import Footer from "@/component/Footer/page";
import DestinationSection from "./destination/page";
import ToursComponent from "./tours/page";
import ExperienceTestimonials from "./experience/page";
import AboutUs from "./about/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header />
        <Home />
        <DestinationSection />
        <ToursComponent />
        <ExperienceTestimonials />
        <AboutUs />
        <Pricing />
        <Newsletter1 />
        <Footer />
      </body>
    </html>
  );
}
